language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pep8
before_script:
  - "pep8 --exclude=migrations --ignore=E501 partuniverse"
# command to run tests
script: bash test.sh
